# Generated by Django 6.0 on 2025-12-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='telefono',
        ),
    ]
